name: 'Notification Action'
description: 'A GitHub Action to send notifications'
author: 'jefferyjob <58850169@qq.com>'

branding:
  icon: 'activity'
  color: 'green'

inputs:
  NOTICE_TYPE:
    description: 'Type of notification (e.g., feishu, dingtalk, workWechat, showDoc)'
    required: true
  MSG_TYPE:
    description: 'Message format (e.g., text, markdown, card)'
    required: true
  STATUS:
    description: 'Deployment status, 1 means success, 0 means failure'
    required: true
  WEBHOOK_URL:
    description: 'Webhook URL for the notification service'
    required: true


runs:
  using: 'composite'
  steps:
    - name: Auto get env
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
          # COMMIT_MESSAGE="PR: ${{ github.event.pull_request.title }}"
          # COMMIT_MESSAGE=$(echo "${{ github.event.pull_request.title }}" | head -n 1 | tr -d '\n' | sed -e 's/["()\\]//g' -e 's/[[:punct:]]//g')
          # 获取并处理 PR 的标题，去掉可能会导致问题的符号
          # COMMIT_MESSAGE=$(echo "${{ github.event.pull_request.title }}" | head -n 1 | tr -d '\n' | sed -e 's/[\"'\'']//g' -e 's/[()\\]//g' -e 's/[[:punct:]]//g')
          # COMMIT_MESSAGE="PR: $COMMIT_MESSAGE"
        else
          echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
          # COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          # COMMIT_MESSAGE=$(echo "${{ github.event.head_commit.message }}" | head -n 1 | tr -d '\n' | sed -e 's/["()\\]//g' -e 's/[[:punct:]]//g')
          # 获取并处理 commit message，去掉可能会导致问题的符号
          # COMMIT_MESSAGE=$(echo "${{ github.event.head_commit.message }}" | head -n 1 | tr -d '\n' | sed -e 's/[\"'\'']//g' -e 's/[()\\]//g' -e 's/[[:punct:]]//g')
        fi
        
        # echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV

    - name: Notify actions
      shell: bash
      env:
        STATUS: ${{ inputs.STATUS }}
        WEBHOOK_URL: ${{ inputs.WEBHOOK_URL }}
        REPO: ${{ github.repository }}
        REPO_URL: ${{ github.event.repository.html_url }}
        WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        BRANCH: ${{ env.BRANCH }}
        COMMIT_USER: ${{ github.actor }}
        COMMIT_SHA: ${{ github.sha }}
        # COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}
      run: |
        chmod +x $GITHUB_ACTION_PATH/notify.sh
        $GITHUB_ACTION_PATH/notify.sh ${{ inputs.NOTICE_TYPE }} ${{ inputs.MSG_TYPE }}
