name: 'Notification Action'
description: 'A GitHub Action to send notifications'
author: 'jefferyjob <58850169@qq.com>'

branding:
  icon: 'activity'
  color: 'green'

inputs:
  NOTICE_TYPE:
    description: 'Type of notification (e.g., feishu, dingtalk, workWechat, showDoc)'
    required: true
  MSG_TYPE:
    description: 'Message format (e.g., text, markdown, card)'
    required: true
  STATUS:
    description: 'Deployment status, 1 means success, 0 means failure'
    required: true
  WEBHOOK_URL:
    description: 'Webhook URL for the notification service'
    required: true


runs:
  using: 'composite'
  steps:
    - name: Auto get env
      shell: bash
      env:
        # pull request
        PR_BRANCH: ${{ github.head_ref }}
        PR_COMMIT_MESSAGE: ${{ github.event.pull_request.title }}
        # commit
        BRANCH: ${{ github.ref_name }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          BRANCH="$PR_BRANCH"
          COMMIT_MESSAGE="$PR_COMMIT_MESSAGE"
        else
          BRANCH="$BRANCH"
          COMMIT_MESSAGE="$COMMIT_MESSAGE"
        fi
        
        COMMIT_MESSAGE=$(echo "$COMMIT_MESSAGE" | head -n 1 | tr -d '\n' | sed -e 's/[\"'\'']//g' -e 's/[()\\]//g' -e 's/[[:punct:]]//g')

        echo "BRANCH=$BRANCH" >> $GITHUB_ENV
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV

    - name: Notify actions
      shell: bash
      env:
        STATUS: ${{ inputs.STATUS }}
        WEBHOOK_URL: ${{ inputs.WEBHOOK_URL }}
        REPO: ${{ github.repository }}
        REPO_URL: ${{ github.event.repository.html_url }}
        WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        BRANCH: ${{ env.BRANCH }}
        COMMIT_USER: ${{ github.actor }}
        COMMIT_SHA: ${{ github.sha }}
        # COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}
      run: |
        chmod +x $GITHUB_ACTION_PATH/notify.sh
        $GITHUB_ACTION_PATH/notify.sh ${{ inputs.NOTICE_TYPE }} ${{ inputs.MSG_TYPE }}
