name: Notify Actions Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: testing  # 指定环境
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send Notification
        uses: ./ # 使用本地 Action
        with:
          NOTICE_TYPE: 'feishu' # 通知类型，可根据需要修改
          MSG_TYPE: 'text'   # 消息类型，可设置为 'text'、'markdown' 等
          WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK }}
          STATUS: '1' # 部署状态，'1' 表示成功，'0' 表示失败

